require 'extensions/extensions'
require 'extensions/ddl_extensions'
require 'globals/ddl_global'
require 'globals/global'
require File.expand_path(File.dirname(__FILE__) + "/../config/environment")
require 'collector/collector'
require 'collector/imap_collector'
require 'collector/file_collector'
require 'collector/rss_collector'
require 'collector/ical_collector'
require 'extractor/stat_extractor'
require 'ir/language_model'
require 'ir/inference_network'
require 'ir/stemmer'
require 'ir/stopwords'
require 'ir/collection'
require 'ir/document'
require 'searcher/indexer'
require 'searcher/searcher'

include Test::Unit::Assertions